language: php
sudo: required
dist: trusty
group: edge
php:
  - '5.6'
  - '7.0'
services:
  - docker
  - docker-compose
  - docker-machine

before_script: composer require atoum/atoum
script: vendor/bin/atoum