version: "2"

services:
  ddkits:
    build: ./ddkits-files/ddkits
    image: ddkits
    container_name: ddkits
    ports:
      - 80:80
      - 443:443
    volumes:
        - ./deploy/docker.sock:/tmp/docker.sock
        - /etc/nginx
        # - ./deploy/nginx:/etc/nginx/sites-available/
        # - ./deploy/nginx:/etc/nginx/sites-enabled/
    networks:
      - ddkits

networks:
  ddkits:

  
